# An example YAML file
name : Default pipeline
comment: To have something when this is deployed
variables:
  file : variables.yaml

properties:
  timeout: 54000 # In step function timeout in seconds

aws_resources: # standalone aws resources

  - name: pandas_layer
    type: lambda_layer
    config:
       layer_entry: "customcode/lambda_layers/pandas"
       bundle_type: custom
       cmd: "rm -rf /asset-output/python  && pip install -r requirements.txt --target /asset-output/python --quiet &&  rm -rf /asset-output/python/scipy* && rm -rf /asset-output/python/numpy*"

  - name: numpy_layer
    type: lambda_layer
    config:
        layer_arn:
                arn: {% if aws_region == 'eu-central-1' %}
                        "arn:aws:lambda:eu-central-1:292169987271:layer:AWSLambda-Python37-SciPy1x:35"
                     {% elif aws_region == 'eu-west-1' %}
                        "arn:aws:lambda:eu-west-1:399891621064:layer:AWSLambda-Python37-SciPy1x:37"
                     {% endif %}
                id: "scipynumpy"

triggers:
  - name: trigger_{{model_name}}
    type: lambda_function
    config:
     entry: "customcode/lambda_functions/{{model_name}}_sfn_trigger"
     index: "handler.py"
     handler: "handler"


groups: # step function

  # - name: "Stepfunction Scheduler"
  #   jobs:
  #     - name : pipeline_queue_executor
  #       config: stepfunction_schedule.yaml
  #       properties:
  #         workers: 2
  #         worker_type : "G.1X"
  #       type: glue_job
  
  - name: "Move files to staging and Prepare Cleansed table"
    jobs:
      - name : leaveofabsence_ingest
        config: leaveofabsence_ingest.yaml
        properties:
          workers: 2
          worker_type : "G.1X"
        type: glue_job

  - name: "Prepare conformed table"
    jobs:
      - name : leaveofabsence_dim_absence
        config: dim_employee_absence.yaml
        properties:
          workers: 2
          worker_type : "G.1X"
        type: glue_job

  - name: "Move processed staging files to archive and end with logging"
    jobs:
      - name : leaveofabsence_move_staging_to_archive
        config: move_staging_to_archive.yaml
        properties:
          workers: 2
          worker_type : "G.1X"
        type: glue_job   


  - name: "Trigger Job"
    jobs:
      - name : trigger_file
        config: trigger_file.yaml
        properties:
          workers: 2
          worker_type : "G.1X"
        type: glue_job 


catch:
  error_equals:
  - States.ALL
  result_path: $.sf-error-info
  groups:
  - name: "Error Lambda"
    jobs:
      - name: errorcatching
        description: "Lambda that put the JSON doc in S3"
        type: lambda_function_logs
        config:
          environment:
            PIPELINE_NAME: {{pipeline_name}}{{stage}}
            CENTRAL_LOGS_BUCKET: {{central_logging_bucket}}
            JOB_NAME: {{pipeline_name}}-error-{{stage}}
            LOG_TYPE: PipelineFailed
            STATUS: FAILURE